swipe:
  3:
    left:
      command: "hyprctl dispatch workspace e+1"
    right:
      command: "hyprctl dispatch workspace e-1"
    up:
      command: "hyprctl dispatch killactive"
    down:
      command: "hyprlock"
  4:
    left:
      command: "playerctl previous"
    right:
      command: "playerctl next"
    up:
      command: "playerctl play-pause"
    down:
      command: "playerctl stop"

pinch:
  in:
    command: "xdotool key ctrl+minus"
  out:
    command: "xdotool key ctrl+plus"

threshold:
  swipe: 0.4
  pinch: 0.1
interval:
  swipe: 0.8
  pinch: 0.1

